version: '3.8'

services:
  evolution_api:
    image: atendareal/evolution-api:latest
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080" # Puerto donde escuchará la API
    environment:
      - SERVER_URL=http://tu_ip_o_dominio:8080
      - DOCKER_NAME=evolution_api
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=TuClaveSegura123 # ¡Cambia esto!
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_HOST=redis_evolution
      - CACHE_REDIS_PORT=6379
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution_net

  redis_evolution:
    image: redis:alpine
    container_name: redis_evolution
    restart: always
    networks:
      - evolution_net

networks:
  evolution_net:
    driver: bridge

volumes:
  evolution_instances:
