services:
  evolution_api:
    image: neutrobox/evolutionapi:v2.3.6-modified
    container_name: evolution_api
    restart: always
    entrypoint: ["node", "dist/main.js"]
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution_net

  redis_evolution:
    image: redis:alpine
    container_name: redis_evolution
    restart: always
    networks:
      - evolution_net

networks:
  evolution_net:
    driver: bridge

volumes:
  evolution_instances:
    driver: local